name: Ping MiniURL Service
on:
  schedule:
    - cron: '*/1 * * * *'  # Every minute (minimum interval)
  workflow_dispatch:  # Allow manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping service
        run: |
          # Ping immediately
          curl -X GET https://se-mpl-b-xgtf.onrender.com
          # Wait 40 seconds and ping again
          sleep 40 && curl -X GET https://se-mpl-b-xgtf.onrender.com
